'Este sera el inicio de plantUMl
@startuml 
skinparam classAttributeIconSize 0
hide circle
show stereotype


ElegirPateador "1" o-left-> "1" EstadoPartido
ElegirPateador "1" o-right-> "1..*" Jugador:selecciona

class ElegirPateador{
    +equipo:Collection
    +estadoDePartido:EstadoPartido

    +mejorPateador():Jugador
    +initialize():ElegirPateador
    +establecerEquipo(unEquipo:Collection, estadoDePartido:EstadoPartido)
    {static}+habiendoGanadoComo(unEquipo:Collection):ElegirPateador
    {static}+habiendoEmpatadoComo(unEquipo:Collection):ElegirPateador
    {static}+habiendoPerdidoComo(unEquipo:Collection):ElegirPateador

}


Jugador <|--down-- Titular
Jugador <|--down-- Suplente

Jugador "1" --right--> "1" NivelDeExperiencia:verifica
class Jugador{
    'Atributos 
    +nombre: String 
    +habilidad: Number
    +experiencia: Number
    +nivelDeExperiencia: NivelDeExperiencia 

    'Metodos
    +Jugador(nombre:String,habilidad:Number,experiencia:Number,nivelDeExperiencia:NivelDeExperiencia)
    +valoracionParaRematar(unEstado:EstadoPartido):Number
    +calcularBasePateador(unEstado:EstadoPartido):Number
    +nombre():String
    +experiencia():Number
    +initialize():Jugador 
    {static} +nombreHabilidadCalidadExperiencia(String,Number,Number,Number):Suplente
    {static} +nombreHabilidadCansancioExperiencia(String,Number,Number,Number):Titular
}

class Titular{
    + cansancio: Number 

    +Titular(nombre:String,habilidad:Number, cansancio:Number, experiencia: Number ,nivelDeExperiencia:NivelDeExperiencia)
    +calcularBasePateador(unEstado: EstadoPartido):Number
    +initialize():Titular
    {static}+nombreHabilidadCansancioExperienciaNivel(String,Number,Number,Number,NivelDeExperiencia):Titular
}
class Suplente{
    +calidad: Number

    +Suplente(nombre:String,habilidad:Number,calidad:Number,experiencia:Number,nivelDeExperiencia:NivelDeExperiencia)
    +calcularBasePateador(unEstado:EstadoPartido):Number
    +initialize():Suplente
    {static}+nombreHabilidadCalidadExperienciaNivel(String,Number,Number,Number,NivelDeExperiencia):Suplente
}




EstadoPartido <|-- EstadoGanado
EstadoPartido <|-- EstadoEmpatado
EstadoPartido <|-- EstadoPerdiendo
class EstadoPartido{

}
class EstadoGanado{

    +bonificar(unValor):Number

}

class EstadoEmpatado{

}

class EstadoPerdiendo{
    +penalizar(unCansancio:Number,unaExperiencia:Number):Number
}




NivelDeExperiencia <|.. Novato

NivelDeExperiencia <|.. Experiementado


interface NivelDeExperiencia <<interface>>{
    +afectar(unValorBase:Number):Number
}

class Novato{

}
class Experiementado{

}





@enduml 
'Este sera la finalizacion de plantuml